version: "3"
services:
  my-clients:
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - app.env
    volumes:
      - ../:/app
    restart: unless-stopped

  postgres-my-clients:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - db.env
    restart: unless-stopped
    volumes:
      - postgres-my-clients:/var/lib/postgresql/data
volumes:
  postgres-my-clients: